### PR TITLE
Fix for Firefox, dependencies, installation method

### PR DESCRIPTION
**Pull request by jgonyea**
I did create a new plugin (non-live on the gpm as of writing this) to assist with disabling HAX if certain files are missing (atools).  You may wish to hold off merging until that's live.

### CODE REVIEW

**Comment by jgonyea** [comment]
Also, this merge should also coincide with the PR for the webcomponents plugin as well.

**Comment by btopro** [comment]
Use the full polyfill instead of lite, very interested in this PR

**Comment by jgonyea** [comment]
@btopro, would you like me to switch it over to the full polyfill and resubmit?

**Comment by btopro** [comment]
maybe align w/ the setting your adding to the webcomponents module and make a method that ensures that the polyfill is applied based on the global setting? That way if other things start to peg off of webcomponents module its like things are requesting that it be included?

**Comment by jgonyea** [comment]
Yes, I'll look at the same option in the wc plugin for the poly fill

**Comment by jgonyea** [comment]
Will resubmit a new PR.

**Pull request closed without merging**
